# Generated by Django 5.2.7 on 2025-10-26 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_penugasan', models.DateTimeField(blank=True, null=True)),
                ('tanggal_selesai', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Belum Dinilai', max_length=50)),
                ('nilai_akhir', models.FloatField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('id_kurator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurasi_ditugaskan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AspekPenilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspek', models.CharField(max_length=100)),
                ('skor', models.IntegerField()),
                ('id_kurasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspek_penilaian', to='repository.kurasi')),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('demo_link', models.URLField(blank=True, max_length=255, null=True)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='poster_images/')),
                ('curation_status', models.CharField(default='pending', max_length=50)),
                ('final_decision', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_pemilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produk_dimiliki', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='kurasi',
            name='id_produk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kurasi', to='repository.produk'),
        ),
        migrations.CreateModel(
            name='RequestSourceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_request', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('id_pemohon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_diajukan', to=settings.AUTH_USER_MODEL)),
                ('id_peninjau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_ditinjau', to=settings.AUTH_USER_MODEL)),
                ('id_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_source_code', to='repository.produk')),
            ],
        ),
    ]
