# Generated by Django 5.2.7 on 2025-10-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Versi URL-friendly dari nama, contoh: web-development', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='produk',
            name='dipublikasikan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produk',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='produk',
            name='kategori',
            field=models.ManyToManyField(blank=True, related_name='produk', to='repository.kategori'),
        ),
        migrations.AddField(
            model_name='produk',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='produk', to='repository.tag'),
        ),
    ]
