# Generated by Django 5.2.7 on 2025-10-28 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_kategori_tag_produk_dipublikasikan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurasi',
            old_name='catatan',
            new_name='catatan_dosen',
        ),
        migrations.RenameField(
            model_name='kurasi',
            old_name='nilai_akhir',
            new_name='nilai_akhir_dosen',
        ),
        migrations.RenameField(
            model_name='kurasi',
            old_name='tanggal_selesai',
            new_name='tanggal_selesai_dosen',
        ),
        migrations.RemoveField(
            model_name='kurasi',
            name='id_kurator',
        ),
        migrations.AddField(
            model_name='aspekpenilaian',
            name='tipe_kurator',
            field=models.CharField(choices=[('dosen', 'Dosen'), ('mitra', 'Mitra')], default='dosen', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kurasi',
            name='catatan_mitra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kurasi',
            name='id_kurator_dosen',
            field=models.ForeignKey(blank=True, limit_choices_to={'peran': 'dosen'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurasi_dosen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kurasi',
            name='id_kurator_mitra',
            field=models.ForeignKey(blank=True, limit_choices_to={'peran': 'mitra'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurasi_mitra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kurasi',
            name='nilai_akhir_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kurasi',
            name='nilai_akhir_mitra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kurasi',
            name='tanggal_selesai_mitra',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aspekpenilaian',
            name='skor',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Kurang'), (2, '2 - Cukup'), (3, '3 - Baik'), (4, '4 - Sangat Baik')], null=True),
        ),
        migrations.AlterField(
            model_name='kurasi',
            name='status',
            field=models.CharField(choices=[('Menunggu Penugasan', 'Menunggu Penugasan'), ('Penilaian Berlangsung', 'Penilaian Berlangsung'), ('Penilaian Dosen Selesai', 'Penilaian Dosen Selesai'), ('Penilaian Mitra Selesai', 'Penilaian Mitra Selesai'), ('Penilaian Lengkap', 'Penilaian Lengkap')], default='Menunggu Penugasan', max_length=50),
        ),
        migrations.AlterField(
            model_name='produk',
            name='curation_status',
            field=models.CharField(choices=[('pending', 'Pending (Menunggu Seleksi)'), ('selected', 'Selected (Terpilih untuk Kurasi)'), ('curators-assigned', 'Curators Assigned (Menunggu Penilaian)'), ('assessment-dosen-done', 'Assessment Dosen Done'), ('assessment-mitra-done', 'Assessment Mitra Done'), ('assessment-complete', 'Assessment Complete (Menunggu Review)'), ('ready-for-publication', 'Ready for Publication (Layak)'), ('revision-minor', 'Revision Minor (Revisi Minor)'), ('needs-coaching', 'Needs Coaching (Perlu Pembinaan)'), ('rejected', 'Rejected (Tidak Layak)'), ('published', 'Published (Dipublikasikan)')], default='pending', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='aspekpenilaian',
            unique_together={('id_kurasi', 'aspek', 'tipe_kurator')},
        ),
    ]
