# Generated by Django 5.2.7 on 2025-10-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_rename_catatan_kurasi_catatan_dosen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='source_code_link',
            field=models.URLField(blank=True, help_text='Link ke source code (GitHub, Drive, dll.)', max_length=255, null=True),
        ),
    ]
