# Generated by Django 5.2.7 on 2025-10-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_produk_source_code_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsourcecode',
            name='alasan_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
