# Generated by Django 5.2.7 on 2025-10-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_requestsourcecode_alasan_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsourcecode',
            name='alasan_request',
            field=models.TextField(blank=True, help_text='Alasan mengapa user meminta akses', null=True),
        ),
    ]
