# Generated by Django 5.2.7 on 2025-11-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_alter_requestsourcecode_alasan_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurasi',
            name='catatan_unit_bisnis',
            field=models.TextField(blank=True, help_text='Catatan final dari Unit Bisnis saat review', null=True),
        ),
    ]
