# Generated by Django 5.2.7 on 2025-12-08 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_kurasi_catatan_unit_bisnis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='curation_status',
            field=models.CharField(choices=[('pending', 'Menunggu Seleksi'), ('selected', 'Terpilih untuk Kurasi'), ('curators-assigned', 'Menunggu Penilaian'), ('assessment-dosen-done', 'Penilaian Dosen Selesai'), ('assessment-mitra-done', 'Penilaian Mitra Selesai'), ('assessment-complete', 'Menunggu Review'), ('ready-for-publication', 'Layak'), ('revision-minor', 'Revisi Minor'), ('needs-coaching', 'Perlu Pembinaan'), ('rejected', 'Tidak Layak'), ('published', 'Dipublikasikan')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='DokumenProyek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keterangan Dokumen')),
                ('file_dokumen', models.FileField(upload_to='project_documents/', verbose_name='File Dokumen')),
                ('tipe_dokumen', models.CharField(default='lainnya', max_length=50, verbose_name='Tipe Dokumen')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='repository.produk')),
            ],
        ),
    ]
