# Generated by Django 5.2.7 on 2025-12-08 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_alter_produk_curation_status_dokumenproyek'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dokumenproyek',
            options={'verbose_name_plural': 'Dokumen Proyek'},
        ),
        migrations.AlterField(
            model_name='dokumenproyek',
            name='file_dokumen',
            field=models.FileField(blank=True, null=True, upload_to='project_documents/', verbose_name='File Dokumen'),
        ),
        migrations.AlterField(
            model_name='dokumenproyek',
            name='keterangan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keterangan File (Atau Link)'),
        ),
        migrations.AlterField(
            model_name='dokumenproyek',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='repository.produk', verbose_name='Proyek'),
        ),
        migrations.AlterField(
            model_name='dokumenproyek',
            name='tipe_dokumen',
            field=models.CharField(choices=[('Laporan Akhir', 'Laporan Akhir'), ('Manual Book', 'Manual Book'), ('Diagram Desain', 'Diagram Desain'), ('Lainnya', 'Lainnya')], default='Lainnya', max_length=50, verbose_name='Jenis Dokumen'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='poster_images/'),
        ),
    ]
