# Generated by Django 5.2.7 on 2025-11-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bidang_keahlian',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_dosen',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_mitra',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nim',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organisasi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='program_studi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
