# Generated by Django 5.2.7 on 2025-11-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_bidang_keahlian_customuser_id_dosen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='program_studi',
            field=models.CharField(blank=True, choices=[('D4 TI', 'D4 Teknik Informatika'), ('D4 TMDJ', 'D4 Teknik Multimedia dan Jaringan'), ('D4 TMD', 'D4 Tenik Multimedia Digital')], max_length=100, null=True),
        ),
    ]
